const home_controller = require('./home_controller')
const auth_controller = require('./auth_controller')
const user_controller = require('./user_controller')
const contact_controller = require('./contact_controller')
const notification_controller = require('./notification_controller')
const message_controller = require('./message_controller')
const group_controller = require('./group_controller')
const setting_controllers = require('./setting_controllers')
const zoom_controller = require('./zoom_controller')

module.exports.home_controller = home_controller
module.exports.auth_controller = auth_controller
module.exports.user_controller = user_controller
module.exports.contact_controller = contact_controller
module.exports.notification_controller = notification_controller
module.exports.message_controller = message_controller
module.exports.group_controller = group_controller
module.exports.setting_controllers = setting_controllers
module.exports.zoom_controller = zoom_controller